// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package knoldus.protos.hello

object HelloProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    knoldus.protos.hello.HelloRequest,
    knoldus.protos.hello.HelloLastName,
    knoldus.protos.hello.HelloReply
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgtoZWxsby5wcm90bxIOa25vbGR1cy5wcm90b3MiawoMSGVsbG9SZXF1ZXN0Eh0KBG5hbWUYASABKAlCCeI/BhIEbmFtZVIEb
  mFtZRI8CgRsYXN0GAIgASgLMh0ua25vbGR1cy5wcm90b3MuSGVsbG9MYXN0TmFtZUIJ4j8GEgRsYXN0UgRsYXN0IjoKDUhlbGxvT
  GFzdE5hbWUSKQoIbGFzdE5hbWUYASABKAlCDeI/ChIIbGFzdE5hbWVSCGxhc3ROYW1lIk0KCkhlbGxvUmVwbHkSJgoHbWVzc2FnZ
  RgBIAEoCUIM4j8JEgdtZXNzYWdlUgdtZXNzYWdlEhcKAmFjGAIgAygFQgfiPwQSAmFjUgJhYzJRCgdHcmVldGVyEkYKCFNheUhlb
  GxvEhwua25vbGR1cy5wcm90b3MuSGVsbG9SZXF1ZXN0Ghoua25vbGR1cy5wcm90b3MuSGVsbG9SZXBseSIAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}